"""
Django settings for personal_management project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Radicale CalDAV sync (Django acts as a client of the local Radicale server).
# If RADICALE_USERNAME and RADICALE_PASSWORD are not set, all sync is a no-op.
RADICALE_URL = os.environ.get("RADICALE_URL", "http://localhost:5232")
RADICALE_USERNAME = os.environ.get("RADICALE_USERNAME")
RADICALE_PASSWORD = os.environ.get("RADICALE_PASSWORD")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-e))d&ir7y&z1xby8x-yt-h*ui_ag#n-@iue=$j_b@kcuq$z@0r",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()
]

CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]

# When the app sits behind a TLS-terminating proxy (Cloudflare Tunnel, Caddy,
# Traefik, etc.) the request hits Django as plain HTTP, but the proxy sets
# X-Forwarded-Proto: https. Enabling this makes request.is_secure() return True
# so CSRF, secure cookies, and same-origin checks behave correctly.
#
# SECURITY: only enable this when the app is unreachable except through the
# proxy. The compose example binds to 127.0.0.1 for exactly this reason —
# otherwise an attacker can spoof X-Forwarded-Proto and bypass HTTPS checks.
if os.environ.get("DJANGO_TRUST_PROXY_HTTPS", "False").lower() in ("1", "true", "yes"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "ninja_extra",
    "ninja_jwt",
    "django_vite",
    "core.apps.CoreConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "personal_management.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "personal_management.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.environ.get("SQLITE_PATH", str(BASE_DIR / "db.sqlite3")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
#
# The frontend is a Vite project at ../frontend. `npm run build` writes hashed
# assets and a manifest into frontend/dist/. We add that dir to STATICFILES_DIRS
# so collectstatic (and runserver in DEBUG) serves it under /static/.

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

FRONTEND_DIST = BASE_DIR.parent / "frontend" / "dist"

STATICFILES_DIRS = [FRONTEND_DIST]

# Whitenoise compresses static files but does NOT re-hash them — Vite already
# produces content-hashed filenames and django-vite's manifest lookups would
# break if whitenoise added a second hash on top.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

# django-vite: in dev_mode the template tags point at the Vite dev server
# (HMR + ESM via http://localhost:3000). In prod they read the manifest written
# by `npm run build` and emit hashed <script>/<link> tags under STATIC_URL.
DJANGO_VITE = {
    "default": {
        "dev_mode": DEBUG,
        "dev_server_port": 3000,
        "manifest_path": FRONTEND_DIST / ".vite" / "manifest.json",
    }
}
