# Generated by Django 6.0.5 on 2026-06-12 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_list_remote_url_task_remote_etag_task_remote_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='remote_event_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('remote_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('remote_etag', models.CharField(blank=True, max_length=255, null=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.list')),
            ],
        ),
    ]
